services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - /home/kamil/docker/heimdall/appdata/:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    networks:
      - nginx_network
    ports:
      - 9000:80
      - 9001:443
    restart: unless-stopped

networks:
  nginx_network:
    external: true
