services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - /home/kamil/docker/heimdall/appdata/:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    networks:
      - docker-network
    ports:
      - 9010:80
      - 9011:443
    restart: unless-stopped

networks:
  docker-network:
    external: true
