services:
  nginx:
    image: nginx:latest
    container_name: nginx-base
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /home/kamil/docker/nginx/appdata/config:/etc/nginx
      - /home/kamil/docker/nginx/appdata/certs:/etc/ssl/private
    networks:
      - docker-network
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  docker-network:
    external: true
