services:
  nginx:
    image: nginx:latest
    container_name: nginx-base
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /home/kamil/docker/nginx/config:/etc/nginx
      - /home/kamil/docker/nginx/certs:/etc/ssl/private
    networks:
      - nginx_network
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  nginx_network:
    name: nginx_network
    driver: bridge
