services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /home/kamil/docker/jellyfin/appdata:/config
      - /mnt/Filmy:/data/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    networks:
      - docker-network
    ports:
      - 8096:8096
    restart: unless-stopped

networks:
  docker-network:
    external: true
